### ISSUE TITLE
Why is my Joe not jumping?

### ISSUE THREAD

**Issue by RuDevOfficial** [MegaChibisX/MegaMan-Unity-8Bit-Engine#3]
![imagen](https://user-images.githubusercontent.com/62806365/78064200-ab52bd80-7391-11ea-927c-4a787bdf55e0.png)

**Comment by MegaChibisX** [comment]
(Sorry for the late response, I completely forgot this existed ^^;)
It may be the Helper.LaunchVelocity thing. Try setting body.velocity = Vector3.up * 500f; instead to make him jump up.

**Comment by RuDevOfficial** [comment]
Oh, you forgot it? Then I might think the engine is abandoned? That sucks
but I still think I can do something with it. Thanks for the reply tho haha.

**Comment by MegaChibisX** [comment]
Yeah, for the time being I have no plans to come back and add stuff.
Really happy it still helped, even if 6 months late!

**Comment by MegaChibisX** [comment]
Try using body.velocity to make the Joe jump.
