### ISSUE TITLE
Upon build, jumping doesn't function correctly.

### ISSUE THREAD

**Issue by Joziah2** [MegaChibisX/MegaMan-Unity-8Bit-Engine#4]
I just downloaded and started messing with this engine a few days ago, and I'm really enjoying the experience so far, but I have encountered a rather crucial bug.

When I attempted to make a build of the game to share a level with my friend, in the build version Megaman couldn't get off of the ground with his jump. He jumps into the air and can't get high enough to clear any jumps, but in the editor he can jump just fine.

I tried the same thing with a completely fresh download of the engine and the same thing happens.

I am using Unity Editor version 2018.3.14f1

**Comment by MegaChibisX** [comment]
Sorry for the long delay! I'll post a fix soon. For now, inside the Player.cs script, you can move the ApplyGravity() function from the bottom of Update() to the bottom of FixedUpdate(). You may also wanna change the gravity strength inside the ApplyGravity() function from 10f to 15f, or a more accurate value in general.

Again sorry for the long delay! I'll be posting an update in a bit.

**Comment by Joziah2** [comment]
I'll give it a go!

Thanks for your hard work, looking forward to the fix! ^-^

**Comment by Joziah2** [comment]
Moving ApplyGravity from Update() to FixedUpdate() seems to have fixed it!! Thanks a lot!

**Comment by MegaChibisX** [comment]
Glad to hear! Thanks for checking it out!
